version: '2.1'
services:

  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    restart: unless-stopped
    environment:
      - TZ=${TIME_ZONE}
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN}
      - ADVERTISE_IP=http://${ADVERTISE_IP}:32400/
      - PLEX_UID=${AUTOMATION_UID}
      - PLEX_GID=${AUTOMATION_GID}
    hostname: infamous-cinema
    volumes:
      - ./plex:/config
      - ./media/transcode:/transcode
      - ./media:/data

  transmission:
    container_name: transmission
    image: dperson/transmission
    restart: unless-stopped
    depends_on:
      - plex
    environment:
      - TZ=${TIME_ZONE}
      - TR_IDLE_SEEDING_LIMIT_ENABLED=true
      - TR_IDLE_SEEDING_LIMIT=600
      - TR_RATIO_LIMIT_ENABLED=true
      - TR_RATIO_LIMIT=4
      - TR_DOWNLOAD_DIR=/downloads
      - TR_INCOMPLETE_DIR_ENABLED=false
      - TR_RENAME_PARTIAL_FILES=true
      - TR_DHT_ENABLED=false
      - TR_PEX_ENABLED=false
      - USERID=${AUTOMATION_UID}
      - GROUPID=${AUTOMATION_GID}
    volumes:
      - ./transmission:/var/lib/transmission-daemon/info
      - ./downloads/complete:/downloads
      - ./downloads/incomplete:/var/lib/transmission-daemon/incomplete

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    depends_on:
      - transmission
      - plex
    environment:
      - TZ=${TIME_ZONE}
      - PUID=${AUTOMATION_UID}
      - PGID=${AUTOMATION_GID}
    volumes:
      - ./sonarr:/config
      - ./media/tv:/tv
      - ./downloads/complete:/downloads

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    depends_on:
      - transmission
      - plex
    environment:
      - TZ=${TIME_ZONE}
      - PUID=${AUTOMATION_UID}
      - PGID=${AUTOMATION_GID}
    volumes:
      - ./radarr:/config
      - ./media/movies:/movies
      - ./downloads/complete:/downloads

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr
    environment:
      - TZ=${TIME_ZONE}
      - PUID=${AUTOMATION_UID}
      - PGID=${AUTOMATION_GID}
    volumes:
      - ./jackett:/config
      - ./downloads/blackhole:/downloads

  ombi:
    container_name: ombi
    image: linuxserver/ombi
    restart: unless-stopped
    depends_on:
      - plex
    network_mode: host
    environment:
      - TZ=${TIME_ZONE}
      - PUID=${AUTOMATION_UID}
      - PGID=${AUTOMATION_GID}
    volumes:
      - ./ombi:/config

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443